# Generated by Django 5.0.4 on 2024-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
